### ISSUE TITLE
Look video on landscape mode

### ISSUE THREAD

**Issue by sergiy-talashko** [fubotv/ooyala-IMA-SDK-phonegap-wrapper#5]
Right now, on iOS, user can rotate video to portrait mode.

Sung say: "lock to landscape on play"

**Comment by fenghuang86** [comment]
I see.

**Comment by fenghuang86** [comment]
I did fix it. Please review and give me your feedback.

Thanks.

**Comment by sergiy-talashko** [comment]
Cool, it's worked.
